test
Signed-off-by: James Talton <talton@gmail.com>

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -88,69 +88,69 @@ jobs:
         run: npm ci
       - run: npm run checks
 
-  awx-e2e:
-    name: AWX E2E
-    needs: packages
-    uses: ./.github/workflows/awx-e2e.yml
-    with:
-      AWX_SERVER: ${{ vars.AWX_SERVER }}
-      SKIP_JOB: ${{ needs.packages.outputs.awx != 'true' }}
-    secrets:
-      AWX_PASSWORD: ${{ secrets.AWX_PASSWORD }}
-      AWX_PROJECT_ID: ${{ secrets.AWX_PROJECT_ID }}
-      AWX_RECORD_KEY: ${{ secrets.AWX_RECORD_KEY }}
+  # awx-e2e:
+  #   name: AWX E2E
+  #   needs: packages
+  #   uses: ./.github/workflows/awx-e2e.yml
+  #   with:
+  #     AWX_SERVER: ${{ vars.AWX_SERVER }}
+  #     SKIP_JOB: ${{ needs.packages.outputs.awx != 'true' }}
+  #   secrets:
+  #     AWX_PASSWORD: ${{ secrets.AWX_PASSWORD }}
+  #     AWX_PROJECT_ID: ${{ secrets.AWX_PROJECT_ID }}
+  #     AWX_RECORD_KEY: ${{ secrets.AWX_RECORD_KEY }}
       
-  eda-e2e:
-    name: EDA E2E
-    needs: packages
-    uses: ./.github/workflows/eda-e2e.yml
-    with:
-      EDA_SERVER: ${{ vars.EDA_SERVER }}
-      SKIP_JOB: ${{ needs.packages.outputs.eda != 'true' }}
-    secrets:
-      EDA_PASSWORD: ${{ secrets.EDA_PASSWORD }}
-      EDA_PROJECT_ID: ${{ secrets.EDA_PROJECT_ID }}
-      EDA_RECORD_KEY: ${{ secrets.EDA_RECORD_KEY }}
+  # eda-e2e:
+  #   name: EDA E2E
+  #   needs: packages
+  #   uses: ./.github/workflows/eda-e2e.yml
+  #   with:
+  #     EDA_SERVER: ${{ vars.EDA_SERVER }}
+  #     SKIP_JOB: ${{ needs.packages.outputs.eda != 'true' }}
+  #   secrets:
+  #     EDA_PASSWORD: ${{ secrets.EDA_PASSWORD }}
+  #     EDA_PROJECT_ID: ${{ secrets.EDA_PROJECT_ID }}
+  #     EDA_RECORD_KEY: ${{ secrets.EDA_RECORD_KEY }}
       
-  hub-e2e:
-    name: HUB E2E
-    needs: packages
-    uses: ./.github/workflows/hub-e2e.yml
-    with:
-      HUB_SERVER: ${{ vars.HUB_SERVER }}
-      SKIP_JOB: ${{ needs.packages.outputs.hub != 'true' }}
-    secrets:
-      HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
-      HUB_PROJECT_ID: ${{ secrets.HUB_PROJECT_ID }}
-      HUB_RECORD_KEY: ${{ secrets.HUB_RECORD_KEY }}
+  # hub-e2e:
+  #   name: HUB E2E
+  #   needs: packages
+  #   uses: ./.github/workflows/hub-e2e.yml
+  #   with:
+  #     HUB_SERVER: ${{ vars.HUB_SERVER }}
+  #     SKIP_JOB: ${{ needs.packages.outputs.hub != 'true' }}
+  #   secrets:
+  #     HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
+  #     HUB_PROJECT_ID: ${{ secrets.HUB_PROJECT_ID }}
+  #     HUB_RECORD_KEY: ${{ secrets.HUB_RECORD_KEY }}
 
-  component:
-    name: Component
-    needs: packages
-    uses: ./.github/workflows/component.yml
-    secrets:
-      COMPONENT_PROJECT_ID: ${{ secrets.COMPONENT_PROJECT_ID }}
-      COMPONENT_RECORD_KEY: ${{ secrets.COMPONENT_RECORD_KEY }}
+  # component:
+  #   name: Component
+  #   needs: packages
+  #   uses: ./.github/workflows/component.yml
+  #   secrets:
+  #     COMPONENT_PROJECT_ID: ${{ secrets.COMPONENT_PROJECT_ID }}
+  #     COMPONENT_RECORD_KEY: ${{ secrets.COMPONENT_RECORD_KEY }}
             
-  success:
-    name: Success
-    runs-on: ubuntu-latest
-    if: ${{ always() }}
-    needs: 
-      - checks
-      - component
-      - awx-e2e
-      - eda-e2e
-      # - hub-e2e
-    steps:
-      - if: ${{ success() }}
-        run: |
-          echo Success
-      - if: ${{ failure() }}
-        run: |
-          echo Failure
-          exit 1
-      - if: ${{ cancelled() }}
-        run: |
-          echo Cancelled
-          exit 1          
+  # success:
+  #   name: Success
+  #   runs-on: ubuntu-latest
+  #   if: ${{ always() }}
+  #   needs: 
+  #     - checks
+  #     - component
+  #     - awx-e2e
+  #     - eda-e2e
+  #     # - hub-e2e
+  #   steps:
+  #     - if: ${{ success() }}
+  #       run: |
+  #         echo Success
+  #     - if: ${{ failure() }}
+  #       run: |
+  #         echo Failure
+  #         exit 1
+  #     - if: ${{ cancelled() }}
+  #       run: |
+  #         echo Cancelled
+  #         exit 1          
